name: Maven Multi Module 

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
        
    - name: Submit Dependency Snapshot
      uses: advanced-security/maven-dependency-submission-action@multi-module

    - name: Build with Maven
      run: mvn -B package --file pom.xml


