name: Maven Multi Module 

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        
    - name: Submit Dependency Snapshot
      uses: advanced-security/maven-dependency-submission-action@multi-module

    - name: Build with Maven
      run: mvn -B package --file pom.xml


